version: '3'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  dbgate:
    image: dbgate/dbgate
    ports:
      - '3001:3000'
    environment:
      - DBGATE_DEFAULT_CONNECTION=${DBGATE_DEFAULT_CONNECTION}
    depends_on:
      - db
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
